### ISSUE TITLE
I'm have troubles testing my sell logic, btest.py keeps on throwing errors

### ISSUE THREAD

**Issue by graetkel** [alpacahq/samplealgo01#13]
(The error I'm getting is on the samplealgo01/samplealgo/btest.py)

I have spent the last two months or so analyzing how the samplealgo01 and multiple other algorithms work. This last week I finally though I had enough information to start building my own algorithm on top of the samplealgo01. I first modified how the order are bought, I had no troubles with this. The error only occurred when I when to modify how stocks are sold. I changed the logic and ran the code but once the code started to run, I got a error that said the snapshot in btest was empty. Since I got an error, I commented out my version of how to sell and uncommented the original version and ran it again. This time the error did not occur. I was a little curious to why, so then I commented out the order.append({...}) that happens in the original sell logic, once I did that an ran the code again I got the same error as before. It looks like if I don't sell it happens.

The next thing I did was go to the beginning of where the error occur and that is here in the btest.py:
```python
        snapshot = {
            symbol: df[df.index < t]
            for symbol, df in price_map.items()
            # sanity check to exclude stale prices
            if t - df[df.index < t].index[-1] < pd.Timedelta('2 days')}
```
It turns out if you hide the order.append({}) in the sell logic or even modify how the sell logic works then the snapshot becomes empty because it does not pass this if statement:
```python
if t - df[df.index < t].index[-1] < pd.Timedelta('2 days')
```

I would like to know why this is happening and is there a work around for it?

**Comment by CruddyShad0w** [comment]
I'm running into the same issue as well. When indexing into the df with -1 in the portion of the line (` df[df.index < t].index[-1]`) causes errors. The error raised is from indexing with a -1 value into an array of 0 items. You can't get the last item of an empty array. 
`
val = getitem(key)
IndexError: index -1 is out of bounds for axis 0 with size 0
`
Anyone have a solution for this?

**Comment by CruddyShad0w** [comment]
I have coded a workaround for this. 
The list of Universe names is outdated that the btest.py uses.
When btest.py makes a call for stock that is no longer in the S&P500 it returns a data`frame of null.
I wore a workaround by wrapping the `snapshot = {` to `account.update(snapshot, t)` in a `try:` `except:` statement.
This skips any empty data frames from inexistent stock getting rid of the index error in line `if t - df[df.index < t].index[-1] < pd.Timedelta('2 days')`

**Comment by CruddyShad0w** [comment]
I fixed your issue after a lot of thinking it came down to simply extending the if statement.
The issue is you can't `df[df.index < t].index[-1]` into a dataframe with a size of 0 there is no index -1.
The solution is to modify the if statement to be:
`
if df[df.index < t].size > 0 and  t - df[df.index < t].index[-1] < pd.Timedelta('2 days')}
`
the if statement will fail if the first condition fails.

**Comment by umitanuki** [comment]
Ah good catch. Will you make a PR to address that issue?

**Comment by CruddyShad0w** [comment]
Yes of course
